name: 19 minutes north
favicon: null
layout_spectrum: 0.9739258359186351
typography_spectrum: 0.8301912578754127
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aba6a0'
    - '#244f86'
    - '#547c86'
    - '#090c13'
    - '#442c20'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.2288415147922933
  rhythmicContrast: 0.25
purpose: []
