typography_spectrum: 0.13992
color:
  brandColors:
    - '#9fcdef'
    - '#6697bf'
    - '#2a6ba5'
    - '#171719'
    - '#ff8d4e'
  brandStrength: 0.3125
  lightness: 0.8125
  saturation: 0.2288415147922933
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2403
analytics:
  google: null
  facebook: null
  twitter: null
name: 19 minutes north
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Welcome to 19 Minutes north
description: Bienvenue sur le site web de la famille STAHLE
purpose: []
